typography_spectrum: 0.23589
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1987364834640175
  lightness: 0.43587764422409236
  saturation: 0.6587528304662555
  rhythmicContrast: 0.5048980223946273
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.77387
analytics:
  google: null
  facebook: null
  twitter: null
name: Larry Wei
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 测试
purpose: []
